# Generated by Django 5.0.3 on 2025-09-06 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_session_id', models.CharField(blank=True, help_text='The ID of the Stripe checkout session.', max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='The ID of the Stripe Payment Intent associated with the transaction.', max_length=255, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time the payment record was created.')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', help_text='The status of the payment (e.g., pending, succeeded, failed).', max_length=50)),
                ('course', models.ForeignKey(blank=True, help_text='The associated course for the payment, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('order', models.ForeignKey(blank=True, help_text='The associated order for the payment, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(blank=True, help_text='The user who initiated the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment Histories',
            },
        ),
    ]
