# Generated by Django 5.0.3 on 2025-09-06 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceWithdrawRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=50)),
                ('transfer_type', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Instapay', 'Instapay'), ('Phone Wallet', 'Phone Wallet')], default='Bank Transfer', max_length=50)),
                ('transfer_status', models.CharField(choices=[('Created', 'Created'), ('Done', 'Done'), ('Refused', 'Refused')], default='Created', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('from_state', models.CharField(blank=True, max_length=250)),
                ('to_state', models.CharField(blank=True, max_length=250)),
                ('confirmation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pickup_scheduled', 'Pickup Scheduled'), ('in_transit_to_warehouse', 'In Transit To Warehouse'), ('delivered_to_warehouse', 'Delivered To Warehouse'), ('in_transit_to_supplier', 'In Transit To Supplier'), ('delivered_successfully', 'Delivered Successfully'), ('failed_delivery', 'Failed Delivery'), ('cancelled', 'Cancelled'), ('accepted_by_supplier', 'Accepted By Supplier'), ('rejected_by_supplier', 'Rejected By Supplier')], default='created', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_shipments', to='accounts.delivery')),
                ('from_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_from_address', to='accounts.address')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to='products.product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_returns', to='accounts.supplier')),
                ('to_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_to_address', to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Withdraw', 'Withdraw'), ('Cash Back', 'Cash Back'), ('Returned Cash Back', 'Returned Cash Back'), ('Returned Product', 'Returned Product'), ('Purchased Products', 'Purchased Products'), ('Refund Failed', 'Refund Failed'), ('Delivery Fee', 'Delivery Fee'), ('Purchased Course', 'Purchased Course'), ('Supplier Transform', 'Supplier Transform')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
