# Generated by Django 5.0.3 on 2025-09-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='credit_card_month',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='credit_card_type',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='credit_card_year',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='credit_cvv',
        ),
    ]
