# Generated by Django 5.0.3 on 2025-09-06 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('course', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_reviews_images/%y/%m/%d')),
                ('ease_of_place_order', models.CharField(blank=True, choices=[('Dissatisfied', 'Dissatisfied'), ('Satisfied', 'Satisfied'), ('Very Satisfied', 'Very Satisfied')], max_length=50, null=True)),
                ('speed_of_delivery', models.CharField(blank=True, choices=[('Dissatisfied', 'Dissatisfied'), ('Satisfied', 'Satisfied'), ('Very Satisfied', 'Very Satisfied')], max_length=50, null=True)),
                ('product_packaging', models.CharField(blank=True, choices=[('Dissatisfied', 'Dissatisfied'), ('Satisfied', 'Satisfied'), ('Very Satisfied', 'Very Satisfied')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='course.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='accounts.customer')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_ratings', to='accounts.delivery')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ratings', to='accounts.supplier')),
            ],
        ),
    ]
